### ISSUE TITLE
Zusätzliche Informationen in Procedure-Referenzen

### ISSUE THREAD

**Issue by linusha** [HowTheyVote/epvotes#177]
Einige Procedures enthalten bis zu drei Sterne (*) und in der Folge römische Zahlen (wir haben I und II gefunden, vielleicht gibt es auch III). Wir vermuten, dass dies mit dem Trilogverfahren zusammen hängt.

- [x] herausfinden, wofür diese Informationen stehen
- [ ] ggf. Informationen beim Scrapen berücksichtigen (momentan schmeißen wir sie weg)

**Comment by tillprochaska** [comment]
<img width="902" alt="Screenshot 2021-04-17 at 18 12 47" src="https://user-images.githubusercontent.com/1512805/115119411-8e8f2500-9fa8-11eb-9537-71d2b6039422.png">

**Comment by linusha** [comment]
This infomation is present via the titles of votes. Procedures are no longer their own entities.
