### ISSUE TITLE
Twitter Cards meta tags are incomplete

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/epvotes#391]
In order to display Twitter cards for vote results, the `og:title` (or alternatively, `twitter:text:title`) meta tags have to be present. In order to support multiple different social platforms, we should probably also use the appropriate Open Graph meta tags for images etc. 

https://ogp.me

**Comment by linusha** [comment]
Fixed in 3c89699865babcb8349114c63528484fb684a7c6
