### ISSUE TITLE
Static file caches do not work for streamed responses

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/epvotes#416]
We stream CSV files to the browser. That presumably doesn't work well with the static file caching we're using.

To reproduce, open the CSV route for a vote that hasn't yet been cached. The CSV is returned as expected. Then reload the page.

Proposed solution: Don't stream the response -- serving a statically cached file should be better anyways.

**Comment by linusha** [comment]
Do you think this is also part of why you could not download a csv file earlier?

**Comment by tillprochaska** [comment]
> Do you think this is also part of why you could not download a csv file earlier?

Yep, pretty sure.
