### ISSUE TITLE
Add JSON endpoint for vote results

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/epvotes#568]
Raw vote results are also available as CSV download which is handy for imports in Excel or data analysis. When building custom web applications or visualizations, being able to fetch the data as JSON could improve the experience, as e.g. JS doesn't include support for working with CSV files in the standard library.

CSV Example: https://howtheyvote.eu/votes/4987.csv

In contrast to CSV, JSON allows for more flexible data structures, so it might be handy to include some additional data, e.g. the title and date of the vote:

This is what a JSON response could look like:

https://howtheyvote.eu/votes/4987.json
```json
{
  "title": "2019 Discharge: EU general budget - European Council and Council",
  "date": "2021-10-19",
  "result": "adopted",
  "members": [
    {
      "first_name": "Magdalena",
      "last_name": "ADAMOWICZ ",
      "position": "FOR",
      ...
    }
  ],
  ...
}
```

Relevant code locations:

* CSV controller action: https://github.com/HowTheyVote/epvotes/blob/main/app/app/Http/Controllers/VotingListsController.php#L102
* CSV feature test: https://github.com/HowTheyVote/epvotes/blob/main/app/tests/Feature/Http/VotingLists/CsvTest.php
* View component that renders the download links: https://github.com/HowTheyVote/epvotes/blob/main/app/resources/views/components/voting-list/download-panel.blade.php
* Routes config: https://github.com/HowTheyVote/epvotes/blob/main/app/routes/web.php#L30
* (CSS: https://github.com/HowTheyVote/epvotes/tree/main/app/resources/css/components)
* Laravel Docs on JSON responses: https://laravel.com/docs/8.x/responses#json-responses

**Comment by linusha** [comment]
Closed with #571
