### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by tillprochaska** [HowTheyVote/epvotes#569]
The readme does not include all the steps necessary to get up an running:

- [ ] Include importing a database dump as an alternative to running migrations and seeders.
- [ ] Include `php artisan key:generate`
- [ ] Include `php artisan config:cache` (possibly add a "FAQ/Help" section)
- [ ] Include `npm run watch` (or `npm run build`) in readme (add that to the Dockerfile as well)

**Comment by linusha** [comment]
We could also add a Contributing paragraph? Mainly to inform people about `composer cs fix` and maybe some documentation pointers,...
Maybe @Alexander-Dubrawski would be so kind to tell us about his experience and we can "reuse" some of the insights.

**Comment by tillprochaska** [comment]
@linusha The checklist from above should contain most of the issues we found when @Alexander-Dubrawski set up the project, though it might not be 100% complete

**Comment by linusha** [comment]
> @linusha The checklist from above should contain most of the issues we found when @Alexander-Dubrawski set up the project, though it might not be 100% complete

I still think pointing out cs-fix and make all would be helpful.
We should also add that one needs to run cache:config after running the tests to make DB requests, that still persists I believe? Also, a note that running artisan test will empty the local db (imo that is related).
