### ISSUE TITLE
Bypassing Docker: Converting HowTheyVote.eu SQL Dump to CSV without Docker Setup

### ISSUE THREAD

**Issue by AndreiCaraman** [HowTheyVote/epvotes#892]
Hi to everyone!
I want to use the HowTheyVote.eu database [dump](https://github.com/HowTheyVote/data) for a Network Science university project but I am having trouble setting up the docker environment because I am not familiar with docker and Laravel. 
Is there a way to directly convert the .sql dump database to a csv without setting up the decker environment?
Thank you!

**Comment by linusha** [comment]
Hey :slightly_smiling_face:,

thanks for your interest in the project!

I do not think that the whole dev environment setup would help you, actually, if you mainly want to use the data for other purposes.

For individual votes we provide the voting data as tabular CSV and JSON files, in case you have not seen that already. The download buttons are at the bottom of the page for each vote, or available via the `/votes/<id>.csv`/`/votes/<id>.json` URLs. 

If you would like to get an overview over the whole data set, I would either recommend a SQL Client that allows you to open the database dump or you can try converters that convert from SLQ -> CSV. I have no experience with these, so I cannot recommend one, unfortunately.

Please be aware, that it is not (easily) possible to just convert the whole database into one tabular form and that working with the raw dump will require JOINs (referencing over multiple tables). When you need specific help with regards to the schema, feel free to reach out!

Also, I need to warn you that we cannot guarantee complete data availability at this time.

**Comment by AndreiCaraman** [comment]
Thank you very much for the response! I ended up manually downloading the files, it was much faster.
